[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  PUBLIC_API_URL = "https://apicontent.marcostorresalarcon.com"

[dev]
  command = "npm run dev"
  targetPort = 4321

[[redirects]]
  from = "/article/*"
  to = "/article/"
  status = 200
