[build]
  command = "npm ci && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 4321

[[redirects]]
  from = "/api/*"
  to = "https://apicontent.marcostorresalarcon.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/article/*"
  to = "/article/"
  status = 200
