// Pipeline de generación de contenido (pasos 2 y 3 del módulo).
//  Paso 2: analizar el material obtenido y relacionarlo con la tecnología
//          actual y la inteligencia artificial.
//  Paso 3: analizar viralidad y storytelling, generar el artículo final y
//          guardarlo en la base con la estructura del proyecto.
//
// El sistema genera VARIAS secciones en la misma corrida (misma frecuencia):
//   - historias     (noticias reales con moraleja, ahora más animadas y sarcásticas)
//   - productividad  (herramientas, tips y trucos de productividad con tecnología e IA)
//   - potencial      (reflexiones y tips para potenciar al ser humano)
// Ver `api/lib/sections.js` para el tono y la configuración de cada sección.

const { articles, getSettings, saveSettings } = require('./db')
const { pickProvider, chat } = require('./llm')
const { pickFreshStory, fetchArticleText } = require('./sources')
const { learnAndResearch } = require('./learn')
const { SECTIONS, getSection, pickFreshAngle } = require('./sections')

const slugify = (s) =>
  s.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim().replace(/\s+/g, '-')
    .slice(0, 80)

// Parsea la respuesta del modelo a objeto, tolerando texto alrededor del JSON.
function parseArticle(raw) {
  let txt = raw.trim()
  const fence = txt.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fence) txt = fence[1].trim()
  const start = txt.indexOf('{')
  const end = txt.lastIndexOf('}')
  if (start !== -1 && end !== -1) txt = txt.slice(start, end + 1)
  return JSON.parse(txt)
}

// Ejecuta los pasos 2 y 3 sobre un material dado y guarda el artículo.
//  section = key u objeto de sección (define el tono y la categoría).
//  source  = { title, text, url } cuando la sección parte de una noticia.
//  topic   = string cuando lo dispara el admin manualmente.
//  angle   = ángulo rotativo para secciones que no parten de noticia.
async function generateArticle({
  section = 'historias', source = null, topic = null, angle = null,
  providerPref = 'auto', rr = 0, category = null, sourceKey = null, playbook = '',
}) {
  const sec = getSection(section)
  const provider = pickProvider(providerPref, rr)

  const userPrompt = sec.buildUserPrompt({ source, topic, angle })

  // Inyectar el playbook aprendido (técnicas de viralidad y aprendizajes) si existe.
  const systemPrompt = playbook
    ? `${sec.system}\n\nGUÍA APRENDIDA (aplícala para maximizar la viralidad de este artículo):\n${playbook}`
    : sec.system

  const raw = await chat(provider, [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ], { json: true, temperature: 0.85 })

  const a = parseArticle(raw)
  if (!a.title || !a.content) throw new Error('El modelo no devolvió título o contenido válidos.')

  const col = await articles()
  let slug = (a.slug && slugify(a.slug)) || slugify(a.title)
  // Evitar colisión de slug.
  if (await col.findOne({ slug })) slug = `${slug}-${Date.now().toString(36).slice(-4)}`

  const now = new Date()
  const sources = []
  if (source?.url) sources.push(source.url)
  if (source?.discussion) sources.push(source.discussion)

  const doc = {
    title: String(a.title).slice(0, 200),
    slug,
    excerpt: String(a.excerpt || '').slice(0, 300),
    category: category || sec.category || a.category || 'Tecnología',
    tags: Array.isArray(a.tags) ? a.tags.map(t => String(t).trim()).filter(Boolean).slice(0, 8) : [],
    content: String(a.content),
    published: true,
    sources,
    autogenerated: true,
    section: sec.key,
    generatedBy: provider.name,
    sourceKey: sourceKey || source?.key || null,
    viralityScore: Number(a.viralityScore) || null,
    viralityNotes: a.viralityNotes || null,
    createdAt: now,
    updatedAt: now,
  }

  const result = await col.insertOne(doc)
  return { ...doc, _id: result.insertedId.toString(), provider: provider.name }
}

// Genera el artículo de UNA sección para la corrida del cron.
//  - Sección tipo 'news': busca una noticia fresca y la convierte en reel con moraleja.
//  - Sección tipo 'topic': elige un ángulo rotativo no usado recientemente.
async function generateForSection(sec, { providerPref, rr, usedKeys, playbook }) {
  if (sec.type === 'news') {
    const story = await pickFreshStory(usedKeys)
    if (!story) return { skipped: true, section: sec.key, reason: 'sin noticias nuevas' }

    const fetched = await fetchArticleText(story.url)
    const text = fetched && fetched.length > 200 ? fetched : (story.summary || fetched || '')

    const article = await generateArticle({
      section: sec.key,
      source: { title: story.title, text, url: story.url, discussion: story.discussion, key: story.key },
      providerPref, rr, sourceKey: story.key, playbook,
    })
    return { ok: true, section: sec.key, article }
  }

  // Sección por ángulo rotativo (productividad, potencial humano).
  const picked = pickFreshAngle(sec, usedKeys)
  if (!picked) return { skipped: true, section: sec.key, reason: 'sin ángulos configurados' }

  const article = await generateArticle({
    section: sec.key,
    angle: picked.angle,
    providerPref, rr, sourceKey: picked.key, playbook,
  })
  return { ok: true, section: sec.key, article }
}

// Flujo completo del cron: aprende y luego genera UN artículo por cada sección
// (todas en la misma corrida = misma frecuencia configurada).
async function runAutogen({ force = false } = {}) {
  const s = await getSettings()

  if (!force && !s.enabled) {
    return { skipped: true, reason: 'desactivado' }
  }

  // Respetar la frecuencia configurada (en minutos): solo generar si pasó el intervalo.
  if (!force && s.lastRunAt) {
    const elapsedMin = (Date.now() - new Date(s.lastRunAt).getTime()) / 6e4
    const freqMin = s.frequencyMinutes || 60
    if (elapsedMin < freqMin - 0.25) {
      return { skipped: true, reason: `frecuencia: faltan ${(freqMin - elapsedMin).toFixed(1)} min` }
    }
  }

  // ANTES DE TODO: fase de aprendizaje. Analiza lo previo e investiga técnicas
  // de viralidad para mejorar el contenido de esta corrida.
  const playbook = await learnAndResearch({ providerPref: s.provider, rr: s._rr || 0 })

  const col = await articles()
  // Claves de fuentes/ángulos ya usados, para no repetir.
  const used = await col
    .find({ autogenerated: true }, { projection: { sourceKey: 1, sources: 1 } })
    .sort({ createdAt: -1 }).limit(200).toArray()
  const usedKeys = new Set()
  for (const d of used) {
    if (d.sourceKey) usedKeys.add(d.sourceKey)
    for (const u of d.sources || []) usedKeys.add(u)
  }

  // Secciones a generar en esta corrida:
  //  - rotateSections = false (default): todas en la misma corrida (misma frecuencia).
  //  - rotateSections = true: una sola sección por corrida, rotando, para abaratar costos.
  const secIdx = (s._sectionRr || 0) % SECTIONS.length
  const toRun = s.rotateSections ? [SECTIONS[secIdx]] : SECTIONS

  // Generar las secciones elegidas. Una sección que falle no tumba al resto.
  const results = []
  let rr = s._rr || 0
  for (const sec of toRun) {
    try {
      const r = await generateForSection(sec, { providerPref: s.provider, rr, usedKeys, playbook })
      results.push(r)
      if (r.article?.sourceKey) usedKeys.add(r.article.sourceKey)
      rr = (rr + 1) % 1000
    } catch (e) {
      results.push({ error: true, section: sec.key, message: e.message })
    }
  }

  const okCount = results.filter(r => r.ok).length
  const errors = results.filter(r => r.error)
  // Avanzar el puntero de rotación una sección por corrida (aunque haya saltos/errores),
  // así con el tiempo se cubren todas por igual.
  const nextSectionRr = s.rotateSections ? (secIdx + 1) % SECTIONS.length : (s._sectionRr || 0)

  if (okCount > 0) {
    await saveSettings({
      lastRunAt: new Date(),
      lastError: errors.length ? `${errors.length} sección(es) con error: ${errors.map(e => e.section + ' (' + e.message + ')').join('; ')}` : null,
      _rr: rr,
      _sectionRr: nextSectionRr,
    })
  } else {
    // Aunque ninguna sección haya generado, avanzar la rotación para no quedarnos
    // atascados en una sección sin material (p. ej. sin noticias nuevas).
    await saveSettings({
      lastError: 'Ninguna sección generó contenido en esta corrida.',
      _sectionRr: nextSectionRr,
    })
  }

  return { ok: okCount > 0, generated: okCount, results }
}

module.exports = { generateArticle, generateForSection, runAutogen, slugify }
