// Fase de aprendizaje: se ejecuta ANTES de generar, en cada corrida del cron.
//  1) Analiza los artículos previos (qué funcionó según su viralidad) para aprender.
//  2) Investiga / recopila herramientas y técnicas de viralidad actuales.
//  3) Guarda un "playbook" acumulativo que se inyecta en la generación para que
//     el contenido mejore en cada ejecución.

const { articles, getSettings, saveSettings } = require('./db')
const { pickProvider, chat } = require('./llm')

const LEARN_SYSTEM = `Eres un estratega de contenido viral y storytelling para redes (reels, TikTok, shorts).
Tu trabajo es APRENDER y MEJORAR de forma continua. Escribes en español peruano (tuteo, "tú").

Recibes: (a) el historial de artículos ya publicados con su puntaje de viralidad y notas, y
(b) el playbook anterior. Debes:
1. Aprender del historial: detectar patrones de lo que funciona mejor y lo que conviene evitar.
2. Investigar y recopilar herramientas, frameworks y técnicas de viralidad ACTUALES y comprobadas
   (ganchos, open loops, pattern interrupts, AIDA, regla de los 3 segundos, storytelling, CTAs, etc.).
3. Combinar todo en un playbook breve y accionable que mejore al anterior (no lo repitas igual: evolucionalo).

Devuelve SIEMPRE un único objeto JSON válido con exactamente estas claves:
{
  "learnings": "2-4 frases con lo aprendido del historial (patrones a repetir y a evitar)",
  "viralityTools": ["lista", "de", "5-8", "técnicas/herramientas de viralidad concretas a aplicar"],
  "playbook": "guía breve y accionable (máx 200 palabras) que el redactor seguirá para el próximo artículo"
}`

// Ejecuta la fase de aprendizaje y devuelve el texto del playbook a inyectar.
// Si falla (p. ej. sin IA configurada), devuelve el último playbook guardado o ''.
async function learnAndResearch({ providerPref = 'auto', rr = 0 } = {}) {
  const s = await getSettings()
  const prev = s.playbook || {}

  try {
    const col = await articles()
    const recent = await col
      .find({ autogenerated: true }, {
        projection: { title: 1, category: 1, viralityScore: 1, viralityNotes: 1, tags: 1, createdAt: 1 },
      })
      .sort({ createdAt: -1 })
      .limit(15)
      .toArray()

    const history = recent.length
      ? recent.map((a, i) =>
          `${i + 1}. [viralidad: ${a.viralityScore ?? '-'}] ${a.title}` +
          (a.viralityNotes ? ` — ${a.viralityNotes}` : '')
        ).join('\n')
      : '(todavía no hay artículos previos: arranca con buenas prácticas generales)'

    const provider = pickProvider(providerPref, rr)
    const raw = await chat(provider, [
      { role: 'system', content: LEARN_SYSTEM },
      { role: 'user', content:
`HISTORIAL DE ARTÍCULOS (más recientes primero):
${history}

PLAYBOOK ANTERIOR:
${prev.text || '(no hay playbook previo)'}

Aprende del historial, investiga técnicas de viralidad actuales y evoluciona el playbook.` },
    ], { json: true, temperature: 0.6, maxTokens: 1000 })

    let parsed
    try {
      let t = raw.trim()
      const start = t.indexOf('{'); const end = t.lastIndexOf('}')
      if (start !== -1 && end !== -1) t = t.slice(start, end + 1)
      parsed = JSON.parse(t)
    } catch {
      parsed = {}
    }

    const tools = Array.isArray(parsed.viralityTools) ? parsed.viralityTools : []
    const text = [
      parsed.learnings ? `Aprendizajes: ${parsed.learnings}` : '',
      tools.length ? `Técnicas de viralidad a aplicar: ${tools.join('; ')}` : '',
      parsed.playbook ? `Playbook: ${parsed.playbook}` : '',
    ].filter(Boolean).join('\n')

    if (text) {
      await saveSettings({
        playbook: {
          text,
          learnings: parsed.learnings || null,
          tools,
          runs: (prev.runs || 0) + 1,
          updatedAt: new Date(),
          by: provider.name,
        },
      })
      return text
    }
    return prev.text || ''
  } catch (e) {
    // No bloquear la generación si el aprendizaje falla; usar el playbook previo.
    await saveSettings({ lastLearnError: e.message })
    return prev.text || ''
  }
}

// Devuelve el playbook guardado (para generación manual sin re-aprender).
async function currentPlaybook() {
  const s = await getSettings()
  return s.playbook?.text || ''
}

module.exports = { learnAndResearch, currentPlaybook }
