// Fase de aprendizaje: se ejecuta ANTES de generar, en cada corrida del cron.
//  1) Analiza los artículos previos (qué funcionó según su viralidad) para aprender.
//  2) Investiga / recopila herramientas y técnicas de viralidad actuales.
//  3) Guarda un "playbook" acumulativo que se inyecta en la generación para que
//     el contenido mejore en cada ejecución.

const { articles, learnings, getSettings, saveSettings } = require('./db')
const { pickProvider, chat } = require('./llm')
const { BASE_STRATEGY } = require('./knowledge')

const LEARN_SYSTEM = `Eres un estratega de contenido viral y storytelling para redes (reels, TikTok, shorts).
Tu trabajo es APRENDER y MEJORAR de forma continua, SIN perder el contexto de lo aprendido antes.
Escribes en español peruano (tuteo, "tú").

Recibes: (a) una ESTRATEGIA BASE permanente que siempre debes respetar y aplicar, (b) el historial de
artículos ya publicados con su puntaje de viralidad y notas, y (c) el historial de aprendizajes anteriores
(lo que ya aprendiste en ciclos previos). Debes:
1. Respetar SIEMPRE la estrategia base (viralidad, retención, conexión con IA y monetización) como fundamento.
2. Aprender del historial de artículos: detectar patrones de lo que funciona mejor y lo que conviene evitar.
3. Conservar y construir sobre los aprendizajes previos: no los descartes, acumulalos y refinalos.
4. Investigar y recopilar herramientas, frameworks y técnicas de viralidad ACTUALES y comprobadas
   (ganchos, open loops, pattern interrupts, AIDA, regla de los 3 segundos, storytelling, CTAs, etc.).
5. Combinar todo en un playbook breve y accionable que mejore al anterior (no lo repitas igual: evolucionalo).

Devuelve SIEMPRE un único objeto JSON válido con exactamente estas claves:
{
  "learnings": "2-4 frases con lo aprendido del historial (patrones a repetir y a evitar)",
  "viralityTools": ["lista", "de", "5-8", "técnicas/herramientas de viralidad concretas a aplicar"],
  "playbook": "guía breve y accionable (máx 200 palabras) que el redactor seguirá para el próximo artículo"
}`

// Ejecuta la fase de aprendizaje y devuelve el texto del playbook a inyectar.
// Si falla (p. ej. sin IA configurada), devuelve el último playbook guardado o ''.
async function learnAndResearch({ providerPref = 'auto', rr = 0 } = {}) {
  const s = await getSettings()
  const prev = s.playbook || {}

  try {
    const col = await articles()
    const recent = await col
      .find({ autogenerated: true }, {
        projection: { title: 1, category: 1, viralityScore: 1, viralityNotes: 1, tags: 1, createdAt: 1 },
      })
      .sort({ createdAt: -1 })
      .limit(15)
      .toArray()

    const history = recent.length
      ? recent.map((a, i) =>
          `${i + 1}. [viralidad: ${a.viralityScore ?? '-'}] ${a.title}` +
          (a.viralityNotes ? ` — ${a.viralityNotes}` : '')
        ).join('\n')
      : '(todavía no hay artículos previos: arranca con buenas prácticas generales)'

    // Historial acumulado de aprendizajes guardado en la base (no perder contexto).
    const learnCol = await learnings()

    // Sembrar la estrategia base en la colección una sola vez (cycle 0, seed).
    if (!(await learnCol.findOne({ seed: true }))) {
      await learnCol.insertOne({
        seed: true,
        cycle: 0,
        learnings: 'Estrategia base 2026 de viralidad y monetización (fundamento permanente).',
        tools: ['regla de los 3 segundos', 'ganchos', 'open loops', 'CTAs', 'afiliados orgánicos', 'productos digitales', 'suscripciones', 'UGC'],
        text: BASE_STRATEGY,
        createdAt: new Date(),
      })
    }

    const pastLearnings = await learnCol
      .find({ seed: { $ne: true } }, { projection: { learnings: 1, tools: 1, cycle: 1, createdAt: 1 } })
      .sort({ createdAt: -1 })
      .limit(8)
      .toArray()

    const learnHistory = pastLearnings.length
      ? pastLearnings
          .slice().reverse()
          .map(l => `· (ciclo ${l.cycle ?? '?'}) ${l.learnings || ''}` +
            (Array.isArray(l.tools) && l.tools.length ? ` [técnicas: ${l.tools.join(', ')}]` : ''))
          .join('\n')
      : '(no hay aprendizajes previos)'

    const provider = pickProvider(providerPref, rr)
    const raw = await chat(provider, [
      { role: 'system', content: LEARN_SYSTEM },
      { role: 'user', content:
`ESTRATEGIA BASE (fundamento permanente, respétala siempre):
${BASE_STRATEGY}

HISTORIAL DE ARTÍCULOS (más recientes primero):
${history}

HISTORIAL DE APRENDIZAJES PREVIOS (más antiguos primero, NO los pierdas, construye sobre ellos):
${learnHistory}

PLAYBOOK ANTERIOR:
${prev.text || '(no hay playbook previo)'}

Aprende del historial, conserva el contexto previo, investiga técnicas de viralidad actuales y evoluciona el playbook.` },
    ], { json: true, temperature: 0.6, maxTokens: 1000 })

    let parsed
    try {
      let t = raw.trim()
      const start = t.indexOf('{'); const end = t.lastIndexOf('}')
      if (start !== -1 && end !== -1) t = t.slice(start, end + 1)
      parsed = JSON.parse(t)
    } catch {
      parsed = {}
    }

    const tools = Array.isArray(parsed.viralityTools) ? parsed.viralityTools : []
    const text = [
      parsed.learnings ? `Aprendizajes: ${parsed.learnings}` : '',
      tools.length ? `Técnicas de viralidad a aplicar: ${tools.join('; ')}` : '',
      parsed.playbook ? `Playbook: ${parsed.playbook}` : '',
    ].filter(Boolean).join('\n')

    if (text) {
      const cycle = (prev.runs || 0) + 1
      const now = new Date()

      // 1) Guardar el ciclo de forma acumulativa (append-only) para no perder contexto.
      await learnCol.insertOne({
        cycle,
        learnings: parsed.learnings || null,
        tools,
        playbook: parsed.playbook || null,
        text,
        by: provider.name,
        articlesSeen: recent.length,
        createdAt: now,
      })

      // 2) Mantener el playbook actual en settings para inyección rápida.
      await saveSettings({
        playbook: {
          text,
          learnings: parsed.learnings || null,
          tools,
          runs: cycle,
          updatedAt: now,
          by: provider.name,
        },
      })
      return text
    }
    return prev.text || BASE_STRATEGY
  } catch (e) {
    // No bloquear la generación si el aprendizaje falla; usar el playbook previo.
    await saveSettings({ lastLearnError: e.message })
    return prev.text || BASE_STRATEGY
  }
}

// Devuelve el playbook guardado (para generación manual sin re-aprender).
// Si aún no hay playbook aprendido, usa la estrategia base como fundamento.
async function currentPlaybook() {
  const s = await getSettings()
  return s.playbook?.text || BASE_STRATEGY
}

module.exports = { learnAndResearch, currentPlaybook }
