// Diagnóstico del autogenerador. Uso:
//   MONGODB_URI="..." node scripts/diag.js
// Muestra la configuración del cron (estado, frecuencia, último error) y los
// últimos artículos autogenerados con su fecha, para ver por qué no se genera.
const { MongoClient } = require('mongodb')
const dns = require('dns')
dns.setServers(['8.8.8.8', '1.1.1.1'])

const uri = process.env.MONGODB_URI
if (!uri) { console.error('Falta MONGODB_URI'); process.exit(1) }

async function run() {
  const client = new MongoClient(uri, { family: 4 })
  await client.connect()
  const db = client.db('content')

  const s = await db.collection('settings').findOne({ _id: 'autogen' })
  console.log('\n=== CONFIGURACIÓN (settings.autogen) ===')
  if (!s) {
    console.log('No existe el documento de settings (el cron nunca corrió o nunca guardó).')
  } else {
    console.log('enabled:          ', s.enabled)
    console.log('frequencyMinutes: ', s.frequencyMinutes ?? '(default 60)')
    console.log('provider:         ', s.provider)
    console.log('rotateSections:   ', s.rotateSections)
    console.log('_cycleCursor:     ', s._cycleCursor ?? 0)
    console.log('lastRunAt:        ', s.lastRunAt)
    console.log('lastError:        ', s.lastError)
    console.log('lastLearnError:   ', s.lastLearnError)
    console.log('playbook ciclos:  ', s.playbook?.runs ?? 0, '· actualizado', s.playbook?.updatedAt)
  }

  const col = db.collection('articles')
  const total = await col.countDocuments({ autogenerated: true })
  const recientes = await col.find({ autogenerated: true }, { projection: { title: 1, section: 1, generatedBy: 1, createdAt: 1 } })
    .sort({ createdAt: -1 }).limit(5).toArray()
  console.log('\n=== ARTÍCULOS AUTOGENERADOS ===')
  console.log('total:', total)
  for (const a of recientes) {
    console.log(`- ${a.createdAt?.toISOString?.() || a.createdAt}  [${a.section || '-'} · ${a.generatedBy || '-'}]  ${a.title}`)
  }

  console.log('\n=== PROVEEDORES (env) ===')
  console.log('OPENAI_API_KEY:   ', process.env.OPENAI_API_KEY ? 'definida' : 'NO definida')
  console.log('DEEPSEEK_API_KEY: ', process.env.DEEPSEEK_API_KEY ? 'definida' : 'NO definida')
  console.log('GROQ_API_KEY:     ', process.env.GROQ_API_KEY ? 'definida' : 'NO definida')
  console.log('GEMINI_API_KEY:   ', (process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY) ? 'definida' : 'NO definida')

  await client.close()
}

run().catch(e => { console.error(e.message); process.exit(1) })
